apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-time-service
  labels:
    app: real-time-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: real-time-service
  template:
    metadata:
      labels:
        app: real-time-service
    spec:
      containers:
      - name: real-time-service
        image: real-time-service:latest
        imagePullPolicy: IfNotPresent
        command:
        - bash
        - -c
        - |
          echo 'Waiting for JobManager to be ready...'
          while ! nc -z flink-jobmanager 8081; do
            sleep 1;
          done;

          echo 'JobManager port is open. Attempting to submit Flink job...'

          MAX_RETRIES=5
          RETRY_COUNT=0
          until flink run -m flink-jobmanager:8081 /opt/flink/usrlib/real-time-service.jar; do
            RETRY_COUNT=$((RETRY_COUNT+1))
            if [ ${RETRY_COUNT} -ge ${MAX_RETRIES} ]; then
              echo 'Failed to submit Flink job after ${MAX_RETRIES} attempts. Exiting.'
              exit 1
            fi
            echo 'Job submission failed, retrying in 5 seconds... (Attempt ${RETRY_COUNT}/${MAX_RETRIES})'
            sleep 5
          done

          echo 'Flink job submitted successfully.'
          # Keep the container running
          tail -f /dev/null
---
# ConfigMap for the build script
apiVersion: v1
kind: ConfigMap
metadata:
  name: real-time-service-build-script
data:
  build.sh: |
    #!/bin/bash
    echo "Building real-time-service image..."
    cd /workspace/real-time-service
    docker build -t real-time-service:latest .
---
# Job to build the real-time-service image
apiVersion: batch/v1
kind: Job
metadata:
  name: real-time-service-build
spec:
  template:
    spec:
      containers:
      - name: docker-build
        image: docker:latest
        command:
        - /bin/sh
        - -c
        - /scripts/build.sh
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: workspace
          mountPath: /workspace
        - name: build-script
          mountPath: /scripts
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: workspace
        hostPath:
          path: /path/to/your/project/root
      - name: build-script
        configMap:
          name: real-time-service-build-script
          defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 3