services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"   # HDFS Web UI
      - "8020:8020"   # HDFS RPC
    volumes:
      - ./docker-volumes/namenode_data:/hadoop/dfs/name
    networks:
      - app-network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    volumes:
      - ./docker-volumes/datanode_data:/hadoop/dfs/data
    networks:
      - app-network

  spark-master:
    image: apache/spark:3.5.0-hadoop3
    container_name: spark-master
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "8080:8080"
      - "7077:7077"
    mem_limit: 4g
    volumes:
      - ./batch-training-service/target/batch-training-service.jar:/opt/spark-apps/batch-training-service.jar
      - ./docker-volumes/spark_master_app_logs:/opt/spark-apps/logs
      - ./docker-volumes/spark_master_spark_logs:/opt/spark/logs
    depends_on:
      - namenode
      - redis
    networks:
      - app-network

  spark-worker:
    image: apache/spark:3.5.0-hadoop3
    container_name: spark-worker
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    mem_limit: 8g
    volumes:
      - ./docker-volumes/spark_worker_app_logs:/opt/spark-apps/logs
      - ./docker-volumes/spark_worker_daemon_logs:/opt/spark/logs
    depends_on:
      - spark-master
      - datanode
      - redis
    networks:
      - app-network
  spark-worker-2:
    image: apache/spark:3.5.0-hadoop3
    container_name: spark-worker-2
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    mem_limit: 8g
    volumes:
      - ./docker-volumes/spark_worker_app_logs:/opt/spark-apps/logs
      - ./docker-volumes/spark_worker_daemon_logs:/opt/spark/logs
    depends_on:
      - spark-master
      - datanode
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./docker-volumes/redis_data:/data
    networks:
      - app-network
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./docker-volumes/mongo_data:/data/db
    networks:
      - app-network

volumes:
  namenode_data:
  datanode_data:
  redis_data:
  spark_master_app_logs:
  spark_master_spark_logs:
  spark_worker_app_logs:
  spark_worker_daemon_logs:
  mongo_data:

networks:
  app-network:
    driver: bridge