services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"   # HDFS Web UI
      - "8020:8020"   # HDFS RPC
    volumes:
      - ./namenode_data:/hadoop/dfs/name
    networks:
      - app-network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    volumes:
      - ./datanode_data:/hadoop/dfs/data
    networks:
      - app-network

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    environment:
      - ENABLE_INIT_DAEMON=false
      - SPARK_MODE=master
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "8080:8080"
    volumes:
      - ./batch-training-service/target/batch-training-service.jar:/opt/spark-apps/batch-training-service.jar
      - ./spark_master_app_logs:/opt/spark-apps/logs
      - ./spark_master_spark_logs:/opt/spark/logs
    depends_on:
      - namenode
      - redis
    networks:
      - app-network

  spark-worker:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker
    environment:
      - ENABLE_INIT_DAEMON=false
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - ./spark_worker_app_logs:/opt/spark-apps/logs
      - ./spark_worker_daemon_logs:/opt/spark/logs

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    environment:
      - ENABLE_INIT_DAEMON=false
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - ./spark_worker_app_logs:/opt/spark-apps/logs
      - ./spark_worker_daemon_logs:/opt/spark/logs

    depends_on:
      - spark-master
      - datanode
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis_data:/data
    networks:
      - app-network

volumes:
  namenode_data:
  datanode_data:
  redis_data:
  spark_master_app_logs:
  spark_master_spark_logs:
  spark_worker_app_logs:
  spark_worker_daemon_logs:


networks:
  app-network:
    driver: bridge