apiVersion: apps/v1
kind: Deployment
metadata:
  name: namenode
  labels:
    app: namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
      - name: namenode
        image: bde2020/hadoop-namenode
        env:
        - name: CLUSTER_NAME
          value: test
        - name: CORE_CONF_fs_defaultFS
          value: hdfs://namenode:8020
        ports:
        - containerPort: 9870
          name: web-ui
        - containerPort: 8020
          name: hdfs
        volumeMounts:
        - name: namenode-data
          mountPath: /hadoop/dfs/name
      volumes:
      - name: namenode-data
        persistentVolumeClaim:
          claimName: namenode-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  selector:
    app: namenode
  ports:
  - name: web-ui
    port: 9870
    targetPort: 9870
  - name: hdfs
    port: 8020
    targetPort: 8020
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namenode-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi