apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: data-importer
  name: data-importer
  namespace: movies-rating
spec:
  containers:
    - args:
        - -c
        - "\n  set -e;\n\n  echo 'Waiting for HDFS to become available...';\n  until hdfs dfs -ls /; do\n    sleep 5;\n  done;\n\n  # KEY FIX: Wait for the NameNode to exit Safe Mode\n  echo 'Waiting for NameNode to exit Safe Mode...';\n  until hdfs dfsadmin -Dfs.defaultFS=hdfs://namenode:8020 -safemode get | grep -q 'Safe mode is OFF'; do\n    sleep 5;\n  done;\n  echo 'NameNode has exited Safe Mode. Proceeding with data import.';\n\n  echo 'HDFS is ready. Image is old, updating package sources to archive...';\n  sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list;\n  sed -i 's/security.debian.org/archive.debian.org/g' /etc/apt/sources.list;\n  sed -i '/stretch-updates/d' /etc/apt/sources.list;\n\n  echo 'Installing dependencies from archive...';\n  apt-get update && apt-get install -y wget unzip;\n\n  echo 'Dependencies installed successfully.';\n  echo 'Downloading MovieLens ml-latest 33M ratings dataset...';\n  wget https://files.grouplens.org/datasets/movielens/ml-latest.zip -O /tmp/ml-latest.zip;\n\n  echo 'Extracting dataset...';\n  unzip /tmp/ml-latest.zip -d /tmp/;\n\n  echo 'Creating /input directory in HDFS...';\n  hdfs dfs -Dfs.defaultFS=hdfs://namenode:8020 -mkdir -p /input;\n\n  echo 'Copying data files to HDFS...';\n  hdfs dfs -Dfs.defaultFS=hdfs://namenode:8020 -put /tmp/ml-latest/*.csv /input/;\n\n  echo 'Data import finished successfully! \U0001F389';\n"
      command:
        - /bin/bash
      image: bde2020/hadoop-namenode
      name: data-importer
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
  restartPolicy: Never
