# Headless service for namenode
apiVersion: v1
kind: Service
metadata:
  name: namenode-headless
  namespace: movies-rating
  labels:
    io.kompose.service: namenode
spec:
  clusterIP: None  # This makes it a headless service
  ports:
    - name: "9870"
      port: 9870
      targetPort: 9870
    - name: "8020"
      port: 8020
      targetPort: 8020
  selector:
    io.kompose.service: namenode

---
# Headless service for datanode
apiVersion: v1
kind: Service
metadata:
  name: datanode-headless
  namespace: movies-rating
  labels:
    io.kompose.service: datanode
spec:
  clusterIP: None  # This makes it a headless service
  ports:
    - name: "9864"
      port: 9864
      targetPort: 9864
    - name: "9866"
      port: 9866
      targetPort: 9866
    - name: "9867"
      port: 9867
      targetPort: 9867
  selector:
    io.kompose.service: datanode

---
# Regular service for namenode (for external access)
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: namenode
  name: namenode
  namespace: movies-rating
spec:
  type: NodePort
  ports:
    - name: "9870"
      port: 9870
      targetPort: 9870
    - name: "8020"
      port: 8020
      targetPort: 8020
  selector:
    io.kompose.service: namenode

---
# Regular service for datanode (for external access)
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: datanode
  name: datanode
  namespace: movies-rating
spec:
  type: NodePort
  ports:
    - name: "9864"
      port: 9864
      targetPort: 9864
  selector:
    io.kompose.service: datanode