apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: jobmanager
  name: jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jobmanager
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: jobmanager
    spec:
      containers:
        - args:
            - jobmanager
          env:
            - name: FLINK_PROPERTIES
              value: |2
                jobmanager.rpc.address: jobmanager
          image: flink:1.17.1-scala_2.12-java11
          name: jobmanager
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
