apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: movies-rating
spec:
  clusterIP: None
  ports:
    - name: internal
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka