apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: external
      port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app: kafka