apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: kafka-data
  name: kafka-data
  namespace: movies-rating
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
