apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: movies-rating
  labels:
    io.kompose.service: kafka
spec:
  type: LoadBalancer
  ports:
    - name: kafka-external
      port: 9094
      targetPort: 9094
      protocol: TCP
  selector:
    io.kompose.service: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-internal
  namespace: movies-rating
  labels:
    io.kompose.service: kafka
spec:
  type: ClusterIP
  ports:
    - name: kafka-internal
      port: 9092
      targetPort: 9092
    - name: kafka-controller
      port: 9093
      targetPort: 9093
  selector:
    io.kompose.service: kafka