apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: namenode
  name: namenode
  namespace: movies-rating
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: namenode
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: namenode
    spec:
      hostname: namenode
      subdomain: namenode
      containers:
        - env:
            - name: CLUSTER_NAME
              value: test
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://namenode:8020
            - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              value: "false"
            - name: HDFS_CONF_dfs_client_use_datanode_hostname
              value: "false"
            - name: HDFS_CONF_dfs_datanode_use_datanode_hostname
              value: "false"
            - name: HDFS_CONF_dfs_namenode_rpc_bind_host
              value: "0.0.0.0"
            - name: HDFS_CONF_dfs_namenode_servicerpc_bind_host
              value: "0.0.0.0"
            - name: HDFS_CONF_dfs_namenode_http_bind_host
              value: "0.0.0.0"
            - name: HDFS_CONF_dfs_namenode_https_bind_host
              value: "0.0.0.0"
          image: bde2020/hadoop-namenode
          name: namenode
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "3Gi"
              cpu: "1500m"
          ports:
            - containerPort: 9870
              protocol: TCP
            - containerPort: 8020
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8020
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 9870
            initialDelaySeconds: 60
            periodSeconds: 30
      restartPolicy: Always