apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: real-time-service
  name: real-time-service
  namespace: movies-rating
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: real-time-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: real-time-service
    spec:
      containers:
        - args:
            - bash
            - -c
            - |2
                echo 'Waiting for JobManager to be ready...'
                while ! nc -z jobmanager 8081; do
                  sleep 1;
                done;

                echo 'JobManager port is open. Attempting to submit Flink job...'

                MAX_RETRIES=5
                RETRY_COUNT=0
                until flink run -m jobmanager:8081 /opt/flink/usrlib/real-time-service.jar; do
                  RETRY_COUNT=$()((RETRY_COUNT+1))
                  if [  -ge  ]; then
                    echo 'Failed to submit Flink job after  attempts. Exiting.'
                    exit 1
                  fi
                  echo 'Job submission failed, retrying in 5 seconds... (Attempt /)'
                  sleep 5
                done

                echo 'Flink job submitted successfully.'
          image: real-time-service
          name: real-time-service
      restartPolicy: Always
