apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: redis
  name: redis
  namespace: movies-rating
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - env:
            - name: REDIS_ARGS
              value: --save 60 1 --appendonly yes --tcp-keepalive 300 --protected-mode no
          image: redis/redis-stack:latest
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
            - containerPort: 8001
              protocol: TCP
      restartPolicy: Always
