apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: spark-worker-2
  name: spark-worker-2
  namespace: movies-rating
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-worker-2
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: spark-worker-2
    spec:
      hostname: spark-worker-2
      containers:
        - env:
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://namenode:8020
            - name: SPARK_MASTER_URL
              value: spark://spark-master:7077
            - name: SPARK_WORKER_WEBUI_PORT
              value: "8086"
            - name: SPARK_WORKER_PORT
              value: "7000"
            - name: SPARK_LOCAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPARK_WORKER_CORES
              value: "2"
            - name: SPARK_WORKER_MEMORY
              value: "2g"
            - name: SERVICE_PRECONDITION
              value: "spark-master:7077"
          image: bde2020/spark-worker:3.3.0-hadoop3.3
          name: spark-worker
          resources:
            requests:
              memory: "1Gi"
              cpu: "4000m"
            limits:
              memory: "4Gi"
              cpu: "4500m"
          ports:
            - containerPort: 8086
              protocol: TCP
              name: webui
            - containerPort: 7000
              protocol: TCP
              name: worker
          readinessProbe:
            httpGet:
              path: /
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 30
      restartPolicy: Always