apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: spark-master
  name: spark-master
  namespace: movies-rating
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-master
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: spark-master
    spec:
      hostname: spark-master
      subdomain: spark-master
      containers:
        - env:
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://namenode:8020
            - name: SPARK_MASTER_HOST
              value: "0.0.0.0"
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
            - name: SPARK_LOCAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPARK_CONF_spark_master_host
              value: "spark-master"
            - name: SPARK_CONF_spark_driver_host
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: bde2020/spark-master:3.3.0-hadoop3.3
          name: spark-master
          resources:
            requests:
              memory: "1Gi"
              cpu: "4000m"
            limits:
              memory: "4Gi"
              cpu: "4500m"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: webui
            - containerPort: 7077
              protocol: TCP
              name: spark
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
      restartPolicy: Always