apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\HP\Desktop\deploy\kompose.exe -f .\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: spark-worker-2
  name: spark-worker-2
  namespace: movies-rating
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-worker-2
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\HP\Desktop\deploy\kompose.exe -f .\docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: spark-worker-2
    spec:
      containers:
        - env:
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://namenode:8020
            - name: SPARK_MASTER_URL
              value: spark://spark-master:7077
          image: bde2020/spark-worker
          name: spark-worker-2
          resources:
            requests:
              memory: "3Gi"
              cpu: "4000m"
            limits:
              memory: "1Gi"
              cpu: "6000m"
          ports:
            - containerPort: 8087
              protocol: TCP
      restartPolicy: Always
