apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\HP\Desktop\deploy\kompose.exe -f .\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: spark-worker-2
  name: spark-worker-2
  namespace: movies-rating
spec:
  type: NodePort
  ports:
    - name: "webui"
      port: 8087
      targetPort: 8087
    - name: "worker"
      port: 7001
      targetPort: 7001
  selector:
    io.kompose.service: spark-worker-2