apiVersion: v1
kind: Service
metadata:
  name: spark-master-headless
  namespace: movies-rating
  labels:
    io.kompose.service: spark-master
spec:
  clusterIP: None
  ports:
    - name: "webui"
      port: 8080
      targetPort: 8080
    - name: "spark"
      port: 7077
      targetPort: 7077
  selector:
    io.kompose.service: spark-master

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: spark-master
  name: spark-master
  namespace: movies-rating
spec:
  type: NodePort
  ports:
    - name: "webui"
      port: 8080
      targetPort: 8080
    - name: "spark"
      port: 7077
      targetPort: 7077
  selector:
    io.kompose.service: spark-master