apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: taskmanager
  name: taskmanager
  namespace: movies-rating
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: taskmanager
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\HP\Documents\FifthYear\Project\movies-rating\kubernetes\kompose.exe -f C:\Users\HP\Documents\FifthYear\Project\movies-rating\docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: taskmanager
    spec:
      containers:
        - args:
            - taskmanager
          env:
            - name: FLINK_PROPERTIES
              value: |2
                jobmanager.rpc.address: jobmanager
                taskmanager.numberOfTaskSlots: 2
          image: flink:1.17.1-scala_2.12-java11
          name: taskmanager
      restartPolicy: Always
