package org.hiast.recommendationsapi;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.data.mongodb.config.EnableMongoAuditing;

/**
 * Main Spring Boot application class for the Recommendations API.
 * This service provides REST endpoints for retrieving movie recommendations
 * generated by the batch training service.
 */
@SpringBootApplication
@EnableConfigurationProperties
@EnableMongoAuditing
public class RecommendationsApiApplication {

    public static void main(String[] args) {
        SpringApplication.run(RecommendationsApiApplication.class, args);
    }

}
