apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: bde2020/spark-master
        ports:
        - containerPort: 8080
          name: web-ui
        - containerPort: 7077
          name: spark
        env:
        - name: CORE_CONF_fs_defaultFS
          value: hdfs://namenode:8020
        volumeMounts:
        - name: spark-apps
          mountPath: /opt/spark-apps
        - name: spark-logs
          mountPath: /opt/spark-apps/logs
        - name: spark-master-logs
          mountPath: /opt/spark/logs
      volumes:
      - name: spark-apps
        persistentVolumeClaim:
          claimName: spark-apps-pvc
      - name: spark-logs
        persistentVolumeClaim:
          claimName: spark-logs-pvc
      - name: spark-master-logs
        persistentVolumeClaim:
          claimName: spark-master-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark-master
  ports:
  - name: web-ui
    port: 8080
    targetPort: 8080
  - name: spark
    port: 7077
    targetPort: 7077
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-apps-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-master-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi