package org.hiast.batch.domain.model;

import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;

/**
 * A container for the user and item factors generated by the ALS model.
 * This is specific to the batch training domain.
 */
public class ModelFactors {
    private final Dataset<Row> userFactors; // Schema: (userId: int, features: vector)
    private final Dataset<Row> itemFactors; // Schema: (itemId: int, features: vector)

    public ModelFactors(Dataset<Row> userFactors, Dataset<Row> itemFactors) {
        this.userFactors = userFactors;
        this.itemFactors = itemFactors;
    }

    public Dataset<Row> getUserFactors() {
        return userFactors;
    }

    public Dataset<Row> getItemFactors() {
        return itemFactors;
    }
}