package org.hiast.batch.domain.model;

import java.io.Serializable;
import java.time.Instant;
import java.util.List;
import java.util.Objects;

/**
 * Represents a collection of movie recommendations for a specific user.
 * This is used to store the recommendations generated by the ALS model.
 */
public class UserRecommendations implements Serializable {
    private static final long serialVersionUID = 1L;

    private final int userId;
    private final List<MovieRecommendation> recommendations;
    private final Instant generatedAt;
    private final String modelVersion;

    /**
     * Constructor for UserRecommendations.
     *
     * @param userId          The user ID.
     * @param recommendations The list of movie recommendations.
     * @param generatedAt     The timestamp when the recommendations were generated.
     * @param modelVersion    The version of the model that generated the recommendations.
     */
    public UserRecommendations(int userId, List<MovieRecommendation> recommendations, 
                              Instant generatedAt, String modelVersion) {
        this.userId = userId;
        this.recommendations = Objects.requireNonNull(recommendations, "recommendations cannot be null");
        this.generatedAt = Objects.requireNonNull(generatedAt, "generatedAt cannot be null");
        this.modelVersion = Objects.requireNonNull(modelVersion, "modelVersion cannot be null");
    }

    public int getUserId() {
        return userId;
    }

    public List<MovieRecommendation> getRecommendations() {
        return recommendations;
    }

    public Instant getGeneratedAt() {
        return generatedAt;
    }

    public String getModelVersion() {
        return modelVersion;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        UserRecommendations that = (UserRecommendations) o;
        return userId == that.userId &&
                Objects.equals(recommendations, that.recommendations) &&
                Objects.equals(generatedAt, that.generatedAt) &&
                Objects.equals(modelVersion, that.modelVersion);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userId, recommendations, generatedAt, modelVersion);
    }

    @Override
    public String toString() {
        return "UserRecommendations{" +
                "userId=" + userId +
                ", recommendations=" + recommendations +
                ", generatedAt=" + generatedAt +
                ", modelVersion='" + modelVersion + '\'' +
                '}';
    }
}
