# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build shared-kernel
        run: mvn -B clean install --file shared-kernel/pom.xml
      - name: Build batch-training-service
        run: mvn -B clean package --file batch-training-service/pom.xml

      - name: Upload shared-kernel JAR
        uses: actions/upload-artifact@v4
        with:
          name: shared-kernel-jar
          path: shared-kernel/target/*.jar

      - name: Upload batch-training-service JAR
        uses: actions/upload-artifact@v4
        with:
          name: batch-training-service-jar
          path: batch-training-service/target/batch-training-service.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download shared-kernel JAR
        uses: actions/download-artifact@v4
        with:
          name: shared-kernel-jar
          path: ./artifacts/

      - name: Download batch-training-service JAR
        uses: actions/download-artifact@v4
        with:
          name: batch-training-service-jar
          path: ./artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*.jar
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}